import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {load} from 'cheerio';
const base=(process.env.BASE_PATH||'/').replace(/\/$/,'');
const pages=[];function scan(dir){for(const f of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,f.name);if(f.isDirectory())scan(p);else if(p.endsWith('.html')&&!p.endsWith('rss/index.html'))pages.push(p);}}scan('dist');
const issues=[];let links=0;
for(const f of pages){const $=load(fs.readFileSync(f,'utf8'));assert($('h1').length,`${f}: missing heading`);assert($('link[rel="canonical"]').length,`${f}: missing canonical`);assert.equal($('meta[name="robots"]').attr('content'),process.env.PRODUCTION==='true'&&!f.includes('/mission-critical-apps/')?undefined:'noindex, nofollow');
 for(const n of $('[href],[src]').toArray())for(const attr of ['href','src']){const v=$(n).attr(attr);if(!v||!v.startsWith('/')||v.startsWith('//'))continue;links++;if(base&&!v.startsWith(base+'/')){issues.push(`${f}: missing base ${v}`);continue;}const u=new URL(v,'https://example.test');const p=decodeURIComponent(u.pathname.slice(base.length));const target=path.join('dist',p);const file=fs.existsSync(target)&&fs.statSync(target).isFile()?target:path.join(target,'index.html');if(!fs.existsSync(file))issues.push(`${f}: missing ${v}`);}
}
const feed=load(fs.readFileSync('dist/rss/index.html','utf8'),{xml:true});
for(const item of feed('item').toArray()){assert.equal(feed(item).find('guid').length,1);assert(feed(item).find('content\\:encoded').text().length>100);}
if(fs.existsSync('evidence/manifest.json')){const m=JSON.parse(fs.readFileSync('evidence/manifest.json'));for(const r of m.records){const $=load(fs.readFileSync(`dist/${r.slug}/index.html`,'utf8'));const normalize=s=>s.replace(/\s+/g,'').replace(/\u00a0/g,'');assert.equal(normalize($('.prose').text()),normalize(r.originalText),`Text changed: ${r.slug}`);for(const id of r.originalIds)assert($('[id]').toArray().some(n=>$(n).attr('id')===id),`Missing fragment ${r.slug}#${id}`);assert.equal($('time').first().attr('datetime'),r.displayDate);assert(feed('guid').toArray().some(n=>feed(n).text()===r.guid));}for(const name of ['pages','posts','authors','tags']){const xml=load(fs.readFileSync(`evidence/sitemap-${name}.xml`,'utf8'),{xml:true});for(const n of xml('url > loc').toArray()){const p=new URL(xml(n).text()).pathname;assert(fs.existsSync(path.join('dist',p,'index.html')),`Missing original route ${p}`);}}}
assert.deepEqual(issues,[]);console.log(`PASS: ${pages.length} pages, ${links} local references, RSS GUIDs/full text, indexing mode; source text, dates, fragments and sitemap coverage checked when evidence is available.`);
